version: 0.2
env:
  secrets_manager:
   KATALON_API_KEY: AWS::CodeBuild::KATALON_API_KEY
phases:
  pre_build:
    commands:
      - docker pull katalonstudio/katalon
  build:
    commands:
      - docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -apiKey=$KATALON_API_KEY -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Booking flows pass"
artifacts:
  files:
    - report/*
reports: #New
  KatalonTestReports: # CodeBuild will create a report group called "KatalonTetReport".
    files: #Store all of the files
      - 'report/JUnit_Report.xml'
