<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gii tr</name>
   <tag></tag>
   <elementGuidId>7a8ab5a9-5337-4c65-8e2b-d7c09f135d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='zing-header']/div[2]/nav/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9af85352-236e-4073-ac08-3d3d0125c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/giai-tri.html</value>
      <webElementGuid>a93a267b-2b72-4b72-9731-80381c17b203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Giải trí</value>
      <webElementGuid>ae7bef1e-e97f-4005-ba71-346a90701f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giải trí</value>
      <webElementGuid>3e800ad9-37c4-46d1-9a9a-28a6925050ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zing-header&quot;)/div[@class=&quot;category-popup active&quot;]/nav[@class=&quot;category-menu&quot;]/div[@class=&quot;page-wrapper&quot;]/ul[@class=&quot;normal-category&quot;]/li[@class=&quot;parent giai-tri&quot;]/a[1]</value>
      <webElementGuid>1a4cd9bc-0c1c-466a-90e7-3953e9c30000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='zing-header']/div[2]/nav/div/ul/li[5]/a</value>
      <webElementGuid>2fbea85c-506c-4409-8b58-c0d39301908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Giải trí')])[2]</value>
      <webElementGuid>bff4dba7-858d-4eb3-a147-bf344c4cf2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dinh dưỡng Thể thao'])[2]/following::a[1]</value>
      <webElementGuid>6013a230-3c68-4c7a-a05f-eff8262b874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hậu trường'])[2]/following::a[2]</value>
      <webElementGuid>b1035b02-40a4-437b-bcc7-241b881b1564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sao'])[2]/preceding::a[1]</value>
      <webElementGuid>318a5307-0d64-46cd-9399-dbe918e39b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Âm nhạc'])[2]/preceding::a[2]</value>
      <webElementGuid>e3b8e7a1-b126-4e59-99d1-50c6db90c2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/giai-tri.html')])[2]</value>
      <webElementGuid>3f254cde-6520-4889-86cc-175b885e3a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[5]/a</value>
      <webElementGuid>1c1876ab-297e-44b6-8707-a426d314d3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/giai-tri.html' and @title = 'Giải trí' and (text() = 'Giải trí' or . = 'Giải trí')]</value>
      <webElementGuid>a21c61e7-24a4-4fb7-8484-ba2a1932a69f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
