<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Lifestyle_more</name>
   <tag></tag>
   <elementGuidId>889a2a16-0bd6-481c-b75f-430e9abe3c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.more</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='zing-header']/div/nav/ul/li[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>65837fae-7fa7-43fb-8289-65f271614844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more</value>
      <webElementGuid>20dec6ce-61dd-4a38-a219-9742fd901d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zing-header&quot;)/div[@class=&quot;page-wrapper&quot;]/nav[@class=&quot;category-menu&quot;]/ul[1]/li[@class=&quot;more&quot;]</value>
      <webElementGuid>d5872701-1fc4-4246-90f0-4e55f7bb0e30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='zing-header']/div/nav/ul/li[9]</value>
      <webElementGuid>e6cbb3b9-3e90-4480-ac00-377c0e2a6e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lifestyle'])[1]/following::li[2]</value>
      <webElementGuid>58a7af4a-8dc7-4de5-9f88-f56ad2562d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sự kiện'])[1]/following::li[3]</value>
      <webElementGuid>b28171e2-c3b0-443d-b6f2-214acc992bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xuất bản'])[2]/preceding::li[1]</value>
      <webElementGuid>0365685a-9338-4489-900c-539cd5fc6f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin tức xuất bản'])[2]/preceding::li[1]</value>
      <webElementGuid>70114492-a859-40fd-8d4e-dc3287ab5812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]</value>
      <webElementGuid>4f2f0b64-ee15-4653-91cc-96ce9091e397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
