<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b6b5b30b-5c0f-49b5-bfb9-53a57a8df81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/homepage_2022/holictis_icon.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2755b0b8-3090-48be-95a9-eb51e686c8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/homepage_2022/holictis_icon.svg</value>
      <webElementGuid>d0d92142-53af-4ef6-85d3-535fe5ecb543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>32c65b23-4a61-4fc1-83a0-8e1034fe2e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>db192e48-dd78-438c-b5ff-fbd9fccb8eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7feada6b-608d-4e56-a6bb-54664e6ae101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_85511515182&quot;)/section[@class=&quot;benefit_section&quot;]/div[@class=&quot;benefit_main_content&quot;]/div[@class=&quot;benefit_list&quot;]/div[@class=&quot;item&quot;]/div[@class=&quot;item-img&quot;]/img[1]</value>
      <webElementGuid>2a04f5d2-4759-4634-b523-adaa64f34617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/homepage_2022/holictis_icon.svg']</value>
      <webElementGuid>00c2d07e-dc1a-4d3e-b4b1-165f0b9508d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/homepage_2022/holictis_icon.svg')]</value>
      <webElementGuid>58fd25c7-c244-44e0-b75f-df59b156c4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_85511515182']/section[5]/div[2]/div/div[5]/div/img</value>
      <webElementGuid>bd931e63-474a-4384-b5fd-ab45c67b387a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/img</value>
      <webElementGuid>c6174843-8931-4674-b3b2-88f4cf6a11f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
