<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Phn hi v h tr truy cp_jfN4p</name>
   <tag></tag>
   <elementGuidId>f35fef6c-7721-4749-8287-76899f43e06b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jfN4p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png' and @alt = 'Google']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16884bac-ffb3-4a61-91ee-092b6a439122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jfN4p</value>
      <webElementGuid>3cbf2025-4825-4b20-8474-bece158d1710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png</value>
      <webElementGuid>2f609309-905e-4e4a-9096-2327892476c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>c61e4add-9c00-4221-8bfd-c283b93ecd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>89d7b16e-cd8f-4ebb-90f1-f04fb11ddca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>8d1c99e2-0525-42f7-b0a1-85a12612a3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46cf10bd-ba1c-434a-b5ed-6925a4bef9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frt</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6114514f-e913-4005-8588-be375f71c05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/img[@class=&quot;jfN4p&quot;]</value>
      <webElementGuid>6d4431bd-1178-4f66-b0f6-686d68121c23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/branding/googlelogo/2x/googlelogo_light_color_92x30dp.png' and @alt = 'Google']</value>
      <webElementGuid>2bdc34dd-1f27-4ad1-a3e8-23679564413c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>25ccf126-a0f7-432a-bfb6-d992022b3645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo']/img</value>
      <webElementGuid>9ee9e737-a1f2-453e-86dd-947f8b4c9c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6fb39ec5-559e-45d9-b181-a2a8e65a4b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
